### ISSUE TITLE
CPU Temperature does not display, always 0* all of time

### ISSUE THREAD

**Issue by phplaw** [luchina-gabriel/BASE-EFI-INTEL-DESKTOP-13THGEN-RAPTOR-LAKE#1]
I think there is issue with SMC, after install successfully, I can not. get CPU Temperature, also can not control fans. Most of monitor app for Mac can not get CPU Temperature as well. 

<img width="232" alt="204858038-67b3344e-dc1c-4c5b-a466-56732ec039d7" src="https://user-images.githubusercontent.com/555124/206757965-7aab12af-c4e8-4039-bc27-a8bd3c9436f6.png">

<img width="341" alt="204858011-d85a4ea8-8562-4c88-a703-5f4e4a007850" src="https://user-images.githubusercontent.com/555124/206757945-e39a0a51-6cae-432a-a04c-b6f25b62950e.png">

Also when you run this command `sudo powermetrics --samplers smc |grep -i "CPU die temperature"` u will get no data 

<img width="988" alt="Screen Shot 2022-12-10 at 12 21 56 AM" src="https://user-images.githubusercontent.com/555124/206757896-2f7914d9-1c72-41c8-9119-4402b394009c.png">

**Comment by luchina-gabriel** [comment]
It is necessary to wait for the VirtualSMC package updates, as this is not an EFI tuning.

Thanks for your feedback ;)
